version: '3.8'
services:
  python_service:
    build: ./smartcalx-service/python_service
    container_name: python_service
    ports:
      - "5000:5000"
  
  node_service:
    build: ./smartcalx-service/python_service/node_service
    container_name: node_service
    ports:
      - "3000:3000"
